version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  web:  # FastAPI
    build: .
    container_name: fastapi_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:  # Celery worker
    build: .
    container_name: celery_worker
    command: celery -A app.core.celery worker --loglevel=info --pool=solo
    env_file:
      - .env
    depends_on:
      - redis

