"""create a new colunm named no_of_dcotors in department

Revision ID: ae0fc5b46f7c
Revises: b39776b9c3a2
Create Date: 2025-09-19 12:51:26.638325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0fc5b46f7c'
down_revision: Union[str, Sequence[str], None] = 'b39776b9c3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('department', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
